import type {Prisma} from '@prisma/client';

export type ActorType = Prisma.ActorCreateInput['type'];
export type EntityKind = Prisma.EntityCreateInput['kind'];
export type EntityDirection =
    NonNullable<Prisma.EntityCreateInput['direction']>;

export const ACTOR_TYPES = {
  BANK_ACCOUNT: 'bank-account',
  ARCADE_MACHINE: 'arcade-machine',
  ARCADE_PLAYER_CARD: 'arcade-player-card',
  ARCADE_PRIZE: 'arcade-prize',
  USDA_FEED: 'usda-feed',
  AGRICULTURE_FARM: 'agriculture-farm',
  AGRICULTURE_RESOURCE_LIBRARY: 'agriculture-resource-library',
  WAREHOUSE: 'warehouse',
  PERSONA: 'persona',
  STAFFING: 'staffing',
  ASSIGNMENT: 'assignment',
  AUTH: 'auth',
  TELEMETRY: 'telemetry',
  CULINARY: 'culinary',
  POINT_OF_SALE_STORE: 'point-of-sale-store',
  GEO: 'geo',
  FREIGHT: 'freight',
  WIKIDATA_CACHE: 'wikidata-cache',
  ENRICHMENT_CACHE: 'enrichment-cache',
  API_CACHE: 'api-cache',
  AI_INSIGHT: 'ai-insight',
  AI_OPERATION: 'ai-operation',
  CHAT_SESSION: 'chat-session',
  POINT_OF_INTEREST: 'point-of-interest',
  AUTH_REFRESH_TOKEN: 'auth_refresh_token',
  AUTH_PROVIDER_GRANT: 'auth_provider_grant',
} as const satisfies Record<string, ActorType>;

export const ENTITY_KINDS = {
  DEPOSIT: 'deposit',
  WITHDRAWAL: 'withdrawal',
  SET: 'set',
  ASSIGNMENT_PAYOUT: 'assignment_payout',
  FREIGHT_PAYMENT: 'freight_payment',
  FREIGHT_LOAD: 'freight_load',
  AI_INSIGHT: 'ai_insight',
  CHAT_MESSAGE: 'chat-message',
  OLLAMA_OPERATION: 'ollama_operation',
  ARCADE_TOPUP: 'arcade_topup',
  ARCADE_SESSION: 'arcade_session',
  ARCADE_PRIZE_REDEMPTION: 'arcade_prize_redemption',
  USDA_REGION: 'usda-region',
  USDA_COUNTRY: 'usda-country',
  USDA_COMMODITY: 'usda-commodity',
  USDA_UNIT: 'usda-unit',
  USDA_ATTRIBUTE: 'usda-attribute',
  AGRICULTURE_PLOT: 'agriculture_plot',
  AGRICULTURE_PLOT_CONDITION: 'agriculture_plot_condition',
  AGRICULTURE_SLOT: 'agriculture_slot',
  AGRICULTURE_CROP_PLAN: 'agriculture_crop_plan',
  AGRICULTURE_TASK: 'agriculture_task',
  AGRICULTURE_INVENTORY_ITEM: 'agriculture_inventory_item',
  AGRICULTURE_INVENTORY_MOVEMENT: 'agriculture_inventory_movement',
  AGRICULTURE_SHIPMENT: 'agriculture_shipment',
  AGRICULTURE_RESOURCE_CATEGORY: 'agriculture_resource_category',
  AGRICULTURE_RESOURCE: 'agriculture_resource',
  WAREHOUSE_ITEM: 'warehouse_item',
  PERSONA: 'persona',
  PERSONA_ATTRIBUTE: 'persona_attribute',
  PERSONA_COMPATIBILITY: 'persona_compatibility',
  STAFFING_ENGAGEMENT: 'staffing_engagement',
  STAFFING_ROLE: 'staffing_role',
  STAFFING_CANDIDATE: 'staffing_candidate',
  STAFFING_SHIFT: 'staffing_shift',
  STAFFING_PLACEMENT: 'staffing_placement',
  ASSIGNMENT: 'assignment',
  ASSIGNMENT_TIMECARD: 'assignment_timecard',
  CULINARY_MENU_ITEM: 'culinary-menu-item',
  CULINARY_PREP_TASK: 'culinary-prep-task',
  CULINARY_SUPPLIER_NEED: 'culinary-supplier-need',
  POINT_OF_SALE_TICKET: 'point-of-sale_ticket',
  AUTH_REFRESH_TOKEN: 'auth_refresh_token',
  AUTH_PROVIDER_GRANT: 'auth_provider_grant',
  TELEMETRY_EVENT: 'telemetry-event',
  MAPTILER_TILE: 'maptiler-tile',
} as const satisfies Record<string, EntityKind>;

export const ENTITY_DIRECTIONS = {
  CREDIT: 'credit',
  DEBIT: 'debit',
} as const satisfies Record<string, EntityDirection>;
