import type { ZoneDefinition, ZoneId } from "./types";

const baseEnv = {
    background: "#05070d",
    fogColor: "#05070d",
    fogNear: 9,
    fogFar: 42,
    keyLight: { color: "#7fe4d0", intensity: 1.1, position: [6, 10, 8] as [number, number, number] },
    fillLight: { color: "#72a8ff", intensity: 0.55, position: [-6, 4, -4] as [number, number, number] },
    rimLight: { color: "#72f0d0", intensity: 0.4, position: [0, 8, -6] as [number, number, number] },
};

export const ZONE_REGISTRY: ZoneDefinition[] = [
    {
        id: "bank",
        label: "Bank",
        description: "Vault ops and ledger",
        glyph: "🏦",
        accent: "#58e0c4",
        spawn: { position: [6, 4, 12], target: [0, 1.4, 0] },
        anchor: [4, 1.6, 6],
        environment: {
            ...baseEnv,
            keyLight: { ...baseEnv.keyLight, color: "#58e0c4" },
        },
    },
    {
        id: "arcade",
        label: "Arcade",
        description: "Tickets, runs, and prizes",
        glyph: "🕹️",
        accent: "#f472ff",
        spawn: { position: [5, 3, 10], target: [0, 1.4, 0] },
        anchor: [5.5, 1.8, 3.5],
        environment: {
            ...baseEnv,
            background: "#0b0613",
            fogColor: "#0b0613",
            keyLight: { ...baseEnv.keyLight, color: "#f472ff" },
        },
    },
    {
        id: "agriculture",
        label: "Agriculture",
        description: "Plots, harvests, and resources",
        glyph: "🌾",
        accent: "#86efac",
        spawn: { position: [7, 3.5, -2], target: [0, 1.4, 0] },
        anchor: [7, 1.5, -2.5],
        environment: {
            ...baseEnv,
            background: "#08100b",
            fogColor: "#08100b",
            keyLight: { ...baseEnv.keyLight, color: "#86efac" },
        },
    },
    {
        id: "warehouse",
        label: "Warehouse",
        description: "Inventory handoff",
        glyph: "📦",
        accent: "#e0e7ff",
        spawn: { position: [-5, 3, -4], target: [0, 1.4, 0] },
        anchor: [-4.5, 1.2, -4.5],
        environment: {
            ...baseEnv,
            background: "#090c14",
            fogColor: "#090c14",
            keyLight: { ...baseEnv.keyLight, color: "#e0e7ff" },
        },
    },
    {
        id: "pos",
        label: "Point of Sale",
        description: "Checkout + receipts",
        glyph: "🧾",
        accent: "#f472b6",
        spawn: { position: [3, 2.8, -7], target: [0, 1.4, 0] },
        anchor: [2.5, 1.2, -6.5],
        environment: {
            ...baseEnv,
            background: "#0d0a0d",
            fogColor: "#0d0a0d",
            keyLight: { ...baseEnv.keyLight, color: "#f472b6" },
        },
    },
    {
        id: "freight",
        label: "Freight",
        description: "Routing + pricing",
        glyph: "🚚",
        accent: "#fbbf24",
        spawn: { position: [-8, 3.2, 1], target: [0, 1.4, 0] },
        anchor: [-8, 1.5, 0],
        environment: {
            ...baseEnv,
            background: "#0f0c06",
            fogColor: "#0f0c06",
            keyLight: { ...baseEnv.keyLight, color: "#fbbf24" },
        },
    },
    {
        id: "culinary",
        label: "Culinary",
        description: "Menus and prep",
        glyph: "🍳",
        accent: "#fb923c",
        spawn: { position: [2, 2.6, -3], target: [0, 1.4, 0] },
        anchor: [1, 1.3, -3],
        environment: {
            ...baseEnv,
            background: "#0d0a07",
            fogColor: "#0d0a07",
            keyLight: { ...baseEnv.keyLight, color: "#fb923c" },
        },
    },
    {
        id: "persona",
        label: "Persona",
        description: "Model compatibility",
        glyph: "👤",
        accent: "#a78bfa",
        spawn: { position: [1, 3, 8], target: [0, 1.4, 0] },
        anchor: [0.5, 1.5, 7.5],
        environment: {
            ...baseEnv,
            background: "#0b0a12",
            fogColor: "#0b0a12",
            keyLight: { ...baseEnv.keyLight, color: "#a78bfa" },
        },
    },
    {
        id: "agency",
        label: "Staffing",
        description: "Assignments + payouts",
        glyph: "🧭",
        accent: "#7dd3fc",
        spawn: { position: [-6, 3, 5], target: [0, 1.4, 0] },
        anchor: [-5, 1.4, 4.5],
        environment: {
            ...baseEnv,
            background: "#081018",
            fogColor: "#081018",
            keyLight: { ...baseEnv.keyLight, color: "#7dd3fc" },
        },
    },
    {
        id: "graphics",
        label: "Graphics Engine",
        description: "Spatial planning",
        glyph: "🛰️",
        accent: "#60a5fa",
        spawn: { position: [0.5, 3.4, 2], target: [0, 1.4, 0] },
        anchor: [0.5, 2, 1],
        environment: {
            ...baseEnv,
            background: "#081018",
            fogColor: "#081018",
            keyLight: { ...baseEnv.keyLight, color: "#60a5fa" },
        },
    },
    {
        id: "laplace",
        label: "Laplace",
        description: "Surface controls",
        glyph: "📈",
        accent: "#94c5ff",
        spawn: { position: [9, 3.2, 5], target: [0, 1.4, 0] },
        anchor: [8.5, 1.6, 4.5],
        environment: {
            ...baseEnv,
            background: "#0a0f16",
            fogColor: "#0a0f16",
            keyLight: { ...baseEnv.keyLight, color: "#94c5ff" },
        },
    },
    {
        id: "rpg",
        label: "Fantasy RPG",
        description: "Quests and skills",
        glyph: "⚔️",
        accent: "#fbb6ce",
        spawn: { position: [-2, 4, -9], target: [0, 1.4, 0] },
        anchor: [-1, 2.6, -8],
        environment: {
            ...baseEnv,
            background: "#0e0a10",
            fogColor: "#0e0a10",
            keyLight: { ...baseEnv.keyLight, color: "#fbb6ce" },
        },
    },
];

export const getZoneById = (id: ZoneId): ZoneDefinition | undefined => ZONE_REGISTRY.find((z) => z.id === id);

export const getZoneIndex = (id: ZoneId): number => ZONE_REGISTRY.findIndex((z) => z.id === id);
